title: ArduinoJson
description: C++ JSON library for IoT. Simple and efficient.
author: BenoitBlanchon
baseurl: ""
url: "https://arduinojson.org"
repository: bblanchon.github.io/ArduinoJson
permalink: pretty
logo: /images/logo.svg

highlighter: rouge
markdown: kramdown
kramdown:
  input: GFM
  hard_wrap: false

plugins:
  - jemoji
  - jekyll-sitemap
  - jekyll-redirect-from
  - jekyll-seo-tag
  - jekyll-feed

exclude:
  - Gemfile
  - Gemfile.lock

collections:
  apis:
    output: true
    permalink: /api/:path/
  faqs:
    output: true
    permalink: /faq/:path/
  features:
    output: false
  examples:
    output: true
    permalink: /example/:path/
  sections:
    output: true
    permalink: /:path/
